### PR TITLE
feat/TR-2791/math-entry-pci-support-rtl

### PR DESCRIPTION
**Pull request by marpesia**
**Related to:** [TR-2791](https://oat-sa.atlassian.net/browse/TR-2791)

**Description:**

Add support to PCI Math Entry to display on RTL mode.

**Changes:**

- Add CSS rules to support RTL mode with LTR mode compatibility.

**How to check:**
- if you using existing instance, you will need to run migration `sudo -u www-data php index.php '\oat\tao\scripts\tools\Migrations' -c migrate -v 'oat\qtiItemPci\migrations\Version202111150718531465_qtiItemPci' -e qtiItemPci`
- Create a PCI Math Entry item in RTL language. And duplicate it on LTR language.
- Create a test with both items and create TT with RTL language.
- Review test with the Guest user (LTR) and RTL TT.
- Check 4 scenarios (LTR + RTL / LTR + LTR / RTL + RTL / RTL + LTR)

**TAE Environment:**

- http://test-tr-2791.playground.kitchen.it.taocloud.org:49801/
- [credentials](http://playground.kitchen.it.taocloud.org/?p=test-tr-2791_delivery.git;a=blob;f=app/admin.txt;h=3c523e3f3f782c849e7407e8df36d6ef31a60917;hb=refs/heads/master)

**Local test:**

- https://github.com/oat-sa/kitchen-playground/blob/test/tr-2791/files/delivery/composer.json

### CODE REVIEW

**Review by krampstudio — CHANGES_REQUESTED** [review]
Everything works as expected, I've just noticed a small misalignment between the field and the buttons.
- the LTR version:
image
- the RTL version:
image

**Comment by marpesia** [comment]
Updated supporting the rule "Allow bidirectional content where RTL is for Arabic letters and LTR for numbers or mathematical expressions in Latin characters."
Now the mathematical expressions keep the LTR mode always

**Review by meefox — APPROVED** [review]
All good
Screenshot 2021-11-16 at 20 47 26


- [ ] New code is covered by tests
- [x] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by krampstudio — APPROVED** [review]
It works well now :+1: 
- [ ] New code is covered by tests 
- [x] Tests are running successfully (old and new ones) on my local machine 
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] <s>New code is not subject to concurrency issues (if applicable)</s>
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Pull request merged**
