### PR TITLE
Fix/vulnerabilities

### PR DESCRIPTION
**Pull request by jsconan**
### Summary

Fix a vulnerability brought by `mathml-to-latex`.

### Details

The npm link was targeting the old version for the library.

Related issues:
- https://github.com/oat-sa/extension-tao-itemqti-pci/security/dependabot/1
- https://github.com/oat-sa/extension-tao-itemqti-pci/security/dependabot/3

### How to test
- install the PCI
- check that the math rendering works well in the prompt (mathml expressions)

### CODE REVIEW

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
lgtm

**Comment by jsconan** [comment]
Wait: when adding a MathML expression, it does not work. The library is not exactly the same, the bridge needs to be adjusted.
```
core/logger Caught[via window.onerror]: 'TypeError: Mathml2latex.convert is not a function'
```

**Comment by jsconan** [comment]
Issue fixed: 'TypeError: Mathml2latex.convert is not a function'

**Review by btamas — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by marpesia — APPROVED** [review]
Works perfect.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code respects code style rules
- [ ] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`

**Pull request merged**
