### PR TITLE
Audio-recording PCI: allow mp4 recording on iOS

### PR DESCRIPTION
**Pull request by krampstudio**
Related to https://oat-sa.atlassian.net/browse/TR-2875

iOS started to support the MediaRecorder only since version 14.3. iOS supports now only H.264 & AAC contained in mp4 (see https://webkit.org/blog/11353/mediarecorder-api/).
This PR adds the `audio/mp4` mime type in the list of formats to test for the recorder, as the last one (to prevent regressions). Without it the file is created with a `type` and an `undefined` file extension. Hopefully, some browsers are able to guess the file type when downloading, but some others don't (Chrome).

How to test: 
 - run the migration locally so the audio PCI is updated to the version `sudo -u www-data php index.php '\oat\tao\scripts\tools\Migrations' -c migrate -v 'oat\qtiItemPci\migrations\Version202112081649481465_qtiItemPci' -e qtiItemPci` 
 - build a test with an audio recording PCI (compressed format only)
 - take the test with an iOS device 14.3 and/or 15
 - try to download the recorded file in the result tab of the authoring using Chrome and Firefox

Resources:
 - [tae](https://delivery.test-tr2875.playground.kitchen.it.taocloud.org) ([credentials](http://playground.kitchen.it.taocloud.org/?p=test-tr2875_delivery.git;a=blob;f=app/admin.txt;h=70dfddf57ff267fcf3e68201233ebb99e4e0828c;hb=refs/heads/master))
 - [composer.json](https://github.com/oat-sa/kitchen-playground/blob/test/tr2875/files/delivery/composer.json)

### CODE REVIEW

**Review by marpesia — CHANGES_REQUESTED** [review]
Test: record, download and play the audio file.

Linux Chrome
- Checked successfully with compressed audio format.
- Checked successfully with uncompressed audio format.

iOS iPad 14
- Checked successfully with compressed audio.
- Fail with the uncompressed audio format on playing the downloaded audio file.
I get an error trying to open the downloaded audio file. (`.wav` type)
image

Is this on the scope of the ticket?

**Comment by krampstudio** [comment]
> Test: record, download and play the audio file.
> 
> Linux Chrome
> 
>     * Checked successfully with compressed audio format.
> 
>     * Checked successfully with uncompressed audio format.
> 
> 
> iOS iPad 14
> 
>     * Checked successfully with compressed audio.
> 
>     * Fail with the uncompressed audio format on playing the downloaded audio file.
>       I get an error trying to open the downloaded audio file. (`.wav` type)
>       image
> 
> 
> Is this on the scope of the ticket?

I've added a comment to the ticket. iOS doesn't support uncompressed formats, only mp4.

**Review by marpesia — APPROVED** [review]
LGTM

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by meefox — APPROVED** [review]
Tried on ios15 all good!
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
