### PR TITLE
Feature/tao 5270 create composite pci

### PR DESCRIPTION
**Pull request by ssipasseuth**
Requires https://github.com/oat-sa/extension-tao-itemqti/pull/1057

1. Fixed some php unit tests, added `oat\qtiItemPci\test\ImportExportTest` to test the full import/export cycle for a QTI item that contains PCIs (don't worry about the many samples files to test the PCI directory parsers ` test/samples/`)
2. Added export of QTI package including https://oat-sa.atlassian.net/browse/TAO-5271
3. Implemented the last missing AC in https://oat-sa.atlassian.net/browse/TAO-5270:
> TAO PCI and IMS PCI must use their respective xml namespace to prevent conflicts in the QTI XML

Namespaces management:
- The new IMS PCI are created under the namespace: `http://www.imsglobal.org/xsd/portableCustomInteraction_v1`
- The exiting OAT PCI are still created under the namespace: `http://www.imsglobal.org/xsd/portableCustomInteraction`
- The exiting OAT PIC are still created under the ns: `http://www.imsglobal.org/xsd/portableInfoControl`
- All portable element markup now uses: `http://www.w3.org/1999/xhtml`

To test this:
1. Checkout the 2 branches:
    https://github.com/oat-sa/extension-tao-itemqti-pci/pull/99
    https://github.com/oat-sa/extension-tao-itemqti/pull/1057
2. Open the customer interaction manager
3. Upload the new sample IMS PCI package provided in this PR https://github.com/oat-sa/extension-tao-itemqti-pci/blob/71f162d727354d260aa26230a00d55400144d1ff/test/samples/package/imsLikert_v0.1.0.zip
4. Once imported, insert the new PCI in the item.
5. Author it, preview it, deliver it, export it, import it again
6. Add the new pci item to a test, export test, import test, deliver it again
7. regression testing: create a QTI test that includes PCI from an older instance (e.g. branch develop), export it and import in the new code, author it, preview it and deliver it.

### CODE REVIEW

**Comment by siwane** [comment]
I have the following error at item authoring
```[tao]php error(2): Declaration of oat\taoQtiItem\model\qti\interaction\PortableCustomInteraction::feed(oat\taoQtiItem\model\qti\ParserFactory $parser, DOMElement $data, oat\taoQtiItem\model\qti\QtiNamespace $xmlns = NULL) should be compatible with oat\taoQtiItem\model\qti\interaction\CustomInteraction::feed(oat\taoQtiItem\model\qti\ParserFactory $parser, DOMElement $data, $xmlns = '') (PHPERROR)
```

**Comment by siwane** [comment]
I have the following error when I upload an invalid zip

> [tao]php error(8): Undefined variable: pciObject (PHPERROR)
> 	qtiIte

mPci/controller/PciManager.php(137)                common_Logger::handlePHPErrors()

**Comment by ssipasseuth** [comment]
I found an issue during the export caused by the new namespace management, please wait.

**Comment by ssipasseuth** [comment]
Ready for review ! 👍 
Side note: The issues on immediate refresh for new imported PCIs are noted but will be addressed in another story (not really part of the new AC asked here and code change is becoming too huge)

**Comment by ssipasseuth** [comment]
Ready for review ! 👍 
Side note: The issues on immediate refresh for new imported PCIs are noted but will be addressed in another story (not really part of the new AC asked here and code change is becoming too huge)

**Comment by siwane** [comment]
okay, I will check

**Pull request merged**
